url: "https://pdxhackerspace.org"
title: PDX Hackerspace
description: "PDX Hackerspace is an educational 501(c)(3) non-profit hackerspace and makerspace in Portland, Oregon. Tools, workshops, events, and community for hacking, making, and learning."
og_image: "/images/logo-bordered.png"

include:
  - _includes

exclude:
  - SEO-PLAN.md
